// Code generated by "stringer -type=Format -linecomment --trimprefix formatEnd"; DO NOT EDIT.

package clog

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[DefaultFormat-0]
	_ = x[TextFormat-1]
	_ = x[JsonFormat-2]
	_ = x[formatEnd-3]
}

const _Format_name = "DEFAULTTEXTJSON"

var _Format_index = [...]uint8{0, 7, 11, 15, 15}

func (i Format) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Format_index)-1 {
		return "Format(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Format_name[_Format_index[idx]:_Format_index[idx+1]]
}
